In [ ]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)

"""print(df.columns)
print(df.index)
print(df.dtypes)"""

print(df.info())
df.describe()
# OU: df.describe().info()

print("._"*50)

df
dados = df[["Autor","Caracteres"]]
dados.loc[0]
# ^ Vai pegar a primeira linha do dataframe, que é a linha de índice 0.
dados.loc[9, "Caracteres"]
# ^ Vai pegar a linha de índice 9 e a coluna "Caracteres" do dataframe.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               10 non-null     int64
 1   Citação          10 non-null     str
 2   Autor            10 non-null     str
 3   Tags             10 non-null     str
 4   Caracteres       10 non-null     int64
 5   Quantidade_Tags  10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes
None
._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._

np.int64(50)

In [27]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)

resultado =df[df["Caracteres"]>100]
resultado2 =df[df["Caracteres"]<80]
resultado
resultado_f = resultado, resultado2
print(resultado_f)
# Para filtrar o dataframe, você pode usar a seguinte sintaxe: df[df["Nome_da_Coluna"]>valor]. Isso vai retornar todas as linhas do dataframe onde o valor da coluna "Nome_da_Coluna" é maior que o valor especificado.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._
(   ID                                            Citação            Autor  \
0   1  “The world as we have created it is a process ...  Albert Einstein
2   3  “There are only two ways to live your life. On...  Albert Einstein
3   4  “The person, be it gentleman or lady, who has ...      Jane Austen
4   5  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

                                           Tags  Caracteres  Quantidade_Tags
0        change, deep-thoughts, thinking, world         115                4
2  inspirational, life, live, miracle, miracles         131                5
3              aliteracy, books, classic, humor         104                4
4                    be-yourself, inspirational         111                2  ,    ID                                            Citação             Autor  \
5   6  “Try not to become a man of success. Rather be...   Albert Einstein
7   8  “I have not failed. I've just found 10,000 way...  Thomas A. Edison
9  10  “A day without sunshine is like, you know, nig...      Steve Martin

                                          Tags  Caracteres  Quantidade_Tags
5                    adulthood, success, value          67                3
7  edison, failure, inspirational, paraphrased          65                4
9                       humor, obvious, simile          50                3  )

In [31]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)
resultado = df [
    df["Autor"]=="Albert Einstein"
]
resultado

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._

,ID,Citação,Autor,Tags,Caracteres,Quantidade_Tags
0,1,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",115,4
2,3,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles",131,5
5,6,“Try not to become a man of success. Rather be...,Albert Einstein,"adulthood, success, value",67,3

In [ ]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)
df_ordenado = df.sort_values(by="Caracteres", ascending=False)
df_ordenado
# False e True são os valores que definem a ordem de classificação. False significa que a classificação será feita em ordem decrescente, enquanto True significa que a classificação será feita em ordem crescente. A primeira Letra é Maiúscula, pois é uma função do Pandas. A segunda letra é minúscula, pois é um parâmetro da função.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._

,ID,Citação,Autor,Tags,Caracteres,Quantidade_Tags
2,3,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles",131,5
0,1,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",115,4
4,5,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational",111,2
3,4,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor",104,4
1,2,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices",85,2
8,9,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,misattributed-eleanor-roosevelt,85,1
6,7,“It is better to be hated for what you are tha...,André Gide,"life, love",82,2
5,6,“Try not to become a man of success. Rather be...,Albert Einstein,"adulthood, success, value",67,3
7,8,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"edison, failure, inspirational, paraphrased",65,4
9,10,"“A day without sunshine is like, you know, nig...",Steve Martin,"humor, obvious, simile",50,3

In [ ]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)
resultado = df[(df["Caracteres"]>100) & (df["Quantidade_Tags"]<5)]
resultado

# & Significa and "e"

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._

,ID,Citação,Autor,Tags,Caracteres,Quantidade_Tags
0,1,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",115,4
3,4,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor",104,4
4,5,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational",111,2

In [ ]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)
"""indice= df["Caracteres"].idxmax()
indice
print(df.loc[indice])"""

"""indice = df.loc[df["Caracteres"].idxmax()]
print(indice)"""

print(df["Autor"].value_counts())
# A função idxmax() retorna o índice da linha que contém o valor máximo da coluna "Caracteres". Esse índice pode ser usado para acessar a linha correspondente no DataFrame.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._
Autor
Albert Einstein      3
J.K. Rowling         1
Jane Austen          1
Marilyn Monroe       1
André Gide           1
Thomas A. Edison     1
Eleanor Roosevelt    1
Steve Martin         1
Name: count, dtype: int64

In [48]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID"
)
print(df["Autor"].unique())
# A função unique() retorna um array com os valores únicos da coluna "Autor". Isso significa que ele vai listar todos os autores diferentes que aparecem no dataframe, sem repetir nenhum deles.
print(".-"*50)
print(f"---> São {df["Autor"].nunique()} autores")
# A função nunique() retorna o número de valores únicos da coluna "Autor". Isso significa que ele vai contar quantos autores diferentes aparecem no dataframe, sem contar nenhum deles mais de uma vez.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._
<StringArray>
[  'Albert Einstein',      'J.K. Rowling',       'Jane Austen',
    'Marilyn Monroe',        'André Gide',  'Thomas A. Edison',
 'Eleanor Roosevelt',      'Steve Martin']
Length: 8, dtype: str
.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
---> São 8 autores

In [ ]:
import pandas as pd
#df=dataframe
dados_texto= pd.read_csv("citacoes.csv")
print("._"*50)
dados_numericos = pd.read_csv("analise_numpy.csv")
df = pd.merge(
    dados_texto,
    dados_numericos,
    on="ID" )

"""grupo = df.groupby("Autor")["Citação"].count()
print(grupo)"""
# A função groupby() agrupa o dataframe pelo valor da coluna "Autor" e, em seguida, a função count() conta o número de citações para cada autor. O resultado é um novo dataframe com os autores como índice e o número de citações como valores.
"""print("._"*50)
grupo2 = df.groupby("Autor")["Caracteres"].mean()
print(grupo2)"""
# A função groupby() agrupa o dataframe pelo valor da coluna "Autor" e, em seguida, a função mean() calcula a média do número de caracteres para cada autor. O resultado é um novo dataframe com os autores como índice e a média de caracteres como valores.

df["Quantidade_Tags"]=(df["Citação"].str.split().str.len())
df
# A função str.split() divide a string da coluna "Citação" em uma lista de palavras, e a função str.len() conta o número de palavras na lista. O resultado é uma nova coluna "Quantidade_Tags" que contém o número de palavras em cada citação.

._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._

,ID,Citação,Autor,Tags,Caracteres,Quantidade_Tags
0,1,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",115,21
1,2,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices",85,16
2,3,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles",131,26
3,4,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor",104,19
4,5,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational",111,16
5,6,“Try not to become a man of success. Rather be...,Albert Einstein,"adulthood, success, value",67,14
6,7,“It is better to be hated for what you are tha...,André Gide,"life, love",82,19
7,8,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"edison, failure, inspirational, paraphrased",65,12
8,9,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,misattributed-eleanor-roosevelt,85,19
9,10,"“A day without sunshine is like, you know, nig...",Steve Martin,"humor, obvious, simile",50,9

In [19]:
# Sempre que você quiser acessar uma coluna específica do DataFrame, você pode fazer isso de duas maneiras: 1. Usando a notação de colchetes: df['nome_da_coluna'] 2. Usando a notação de ponto: df.nome_da_coluna Ex:
df["Autor"]

# SEmpre será possível ver o último print a não ser que você forçe dois prints

0      Albert Einstein
1         J.K. Rowling
2      Albert Einstein
3          Jane Austen
4       Marilyn Monroe
5      Albert Einstein
6           André Gide
7     Thomas A. Edison
8    Eleanor Roosevelt
9         Steve Martin
Name: Autor, dtype: str